# Copyright (c) 2026 Minsun Kim. All rights reserved. See LICENSE.
"""
F-03: Actionable Guardrail & Policy-as-Code Generation Engine.

Design decision (T-06): the MCP tool-calling policy manifest -- the part
that gates what an agent may touch -- is generated by DETERMINISTIC code,
not the LLM. The LLM is used only for the governance narrative, framework
citations, and suggested controls -- parts that are genuinely generative
and low-stakes if imperfect, unlike the enforcement boundary.

If ANTHROPIC_API_KEY is not set, this module falls back to a clearly
labeled mock response so the rest of the pipeline runs end-to-end without
a key.
"""
from __future__ import annotations

import json
import os
from typing import List, Optional

from .models import MCPToolPolicy, PolicyManifest, RiskLevel, RiskScore, UseCaseIntake

MODEL_NAME = os.environ.get("ANTHROPIC_MODEL", "claude-sonnet-4-5-20250929")
MAX_RETRIES = 2

SYSTEM_PROMPT = """You are a regulatory compliance assistant supporting an enterprise AI \
governance workflow. Given a structured AI use case and its computed risk score, \
respond with ONLY a JSON object (no prose, no markdown fences) matching this schema:

{
  "applicable_frameworks": ["string", ...],   // 2-4 of: NIST AI RMF, EU AI Act, ISO 42001, ISO 23894, OECD AI Principles, GDPR, SOC 2, ISO 27001, HIPAA, PCI DSS, CCPA/PIPEDA
  "governance_narrative": "string",           // 2-3 sentences summarizing the risk profile
  "controls": ["string", ...],                // 4-6 specific, actionable governance controls
  "system_prompt_constraint": "string"        // one paste-able system-prompt clause to mitigate the top risk
}

Ground every framework citation in the actual framework -- do not invent article numbers \
you are not confident about. Only surface HIPAA if the use case involves healthcare data, \
and only surface PCI DSS if it involves payment data."""


def _build_user_prompt(intake: UseCaseIntake, risk: RiskScore) -> str:
    active_factors = [b.factor for b in risk.breakdown if b.active]
    return json.dumps(
        {
            "use_case_name": intake.use_case_name,
            "business_unit": intake.business_unit,
            "description": intake.description,
            "output_type": intake.output_type.value,
            "persona": intake.persona.value,
            "risk_score": risk.total_score,
            "risk_level": risk.risk_level.value,
            "active_risk_factors": active_factors,
        }
    )


def _mock_llm_response(intake: UseCaseIntake, risk: RiskScore) -> dict:
    active = [b.factor for b in risk.breakdown if b.active]
    frameworks = ["NIST AI RMF", "EU AI Act"]
    if any("Personal Data" in f for f in active):
        frameworks.append("GDPR")
    return {
        "applicable_frameworks": frameworks,
        "governance_narrative": (
            f"[MOCK - set ANTHROPIC_API_KEY for live output] '{intake.use_case_name}' "
            f"scores {risk.total_score} ({risk.risk_level.value}) driven by "
            f"{', '.join(active) if active else 'no active risk factors'}."
        ),
        "controls": [
            "Document a data flow diagram for this use case",
            "Assign a named risk owner in the business unit",
            "Log all model inputs/outputs for the audit trail",
            "Schedule a periodic framework re-review",
        ],
        "system_prompt_constraint": (
            "Never reveal, infer, or act on personally identifiable information "
            "unless explicitly authorized by an HITL approval token."
        ),
    }


def _call_llm(intake: UseCaseIntake, risk: RiskScore) -> dict:
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        return _mock_llm_response(intake, risk)

    import anthropic

    client = anthropic.Anthropic(api_key=api_key)
    user_prompt = _build_user_prompt(intake, risk)

    last_error: Optional[Exception] = None
    for _ in range(MAX_RETRIES + 1):
        message = client.messages.create(
            model=MODEL_NAME,
            max_tokens=1000,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": user_prompt}],
        )
        raw_text = "".join(block.text for block in message.content if block.type == "text").strip()
        try:
            return json.loads(raw_text)
        except json.JSONDecodeError as exc:
            last_error = exc
            continue

    raise RuntimeError(f"LLM did not return valid JSON after {MAX_RETRIES + 1} attempts: {last_error}")


# ---------------------------------------------------------------------------
# Deterministic MCP tool-calling policy manifest (T-06: not the LLM's job)
# ---------------------------------------------------------------------------

TOOL_CATEGORIES = ["sql_read", "sql_write", "external_api", "file_export"]


def _derive_mcp_policies(intake: UseCaseIntake, risk: RiskScore) -> List[MCPToolPolicy]:
    high = risk.risk_level == RiskLevel.HIGH
    medium = risk.risk_level == RiskLevel.MEDIUM
    sensitive = intake.personal_data_privacy or intake.sensitive_data_enterprise_ip
    autonomous = intake.autonomous_decision_making
    third_party = intake.third_party_dependency
    security_exposed = intake.security_exposure

    policies: List[MCPToolPolicy] = []

    policies.append(
        MCPToolPolicy(
            tool_category="sql_read",
            allowed=not (high and sensitive),
            requires_hitl_token=sensitive or high,
            condition=(
                "Blocked: high-risk use case with sensitive data may not read data stores directly."
                if (high and sensitive)
                else "Allowed, but requires a valid HITL approval token before execution."
                if (sensitive or high)
                else "Allowed without additional authorization."
            ),
        )
    )
    policies.append(
        MCPToolPolicy(
            tool_category="sql_write",
            allowed=not (autonomous or high),
            requires_hitl_token=True,
            condition=(
                "Blocked: autonomous or high-risk agents may not write to systems of "
                "record without a human in the loop."
                if (autonomous or high)
                else "Allowed with mandatory HITL token on every write."
            ),
        )
    )
    policies.append(
        MCPToolPolicy(
            tool_category="external_api",
            allowed=not (security_exposed and high),
            requires_hitl_token=security_exposed or medium or high,
            condition=(
                "Blocked: high-risk use case with security exposure may not call external APIs."
                if (security_exposed and high)
                else "Allowed; HITL token required given elevated risk."
                if (security_exposed or medium or high)
                else "Allowed without additional authorization."
            ),
        )
    )
    policies.append(
        MCPToolPolicy(
            tool_category="file_export",
            allowed=not high,
            requires_hitl_token=medium or high,
            condition=(
                "Blocked: high-risk use cases may not export files unattended."
                if high
                else "Allowed with HITL token."
                if medium
                else "Allowed without additional authorization."
            ),
        )
    )
    return policies


def generate_policy_manifest(intake: UseCaseIntake, risk: RiskScore) -> PolicyManifest:
    llm_output = _call_llm(intake, risk)
    mcp_policies = _derive_mcp_policies(intake, risk)

    return PolicyManifest(
        use_case_name=intake.use_case_name,
        applicable_frameworks=llm_output["applicable_frameworks"],
        governance_narrative=llm_output["governance_narrative"],
        controls=llm_output["controls"],
        mcp_tool_policies=mcp_policies,
        system_prompt_constraint=llm_output["system_prompt_constraint"],
    )
